### COMAKE2: PLEASE DO NOT DELETE THE FILE
#<cvspath>,trunk/<branch-name>/-,<localrev>,<tag-name>/-,<cleancmd>,<makecmd>,disbuild/-,DEP-<N>,unstable/-
ds/boss/sdk/c/test,,???,???,make clean,make
    quality/autotest/reportlib/cpp,,356,cpp_2-0-1-1_PD_BL,make clean,make,,DEP-2,
    com/btest/gtest,,5718,gtest_1-1-0-0_PD_BL,,sh build.sh,,DEP-2,
    quality/autotest/bmock,,11606,bmock_1-1-4-0_PD_BL,make clean,make,,DEP-1,
    third-64/gtest,,46,gtest_1-4-0-500_PD_BL,,,,DEP-1,
